### ISSUE TITLE
我看你模拟点击微信的代码注释掉了，是不可以使用吗？

### ISSUE THREAD

**Issue by WeiEast** [nekocode/wx_sniffer#1]

**Comment by nekocode** [comment]
可以使用。不过微信那边 getappmsgext 接口一段时间内超过一定数量请求会不返回，所以可能要实现更合理的模拟点击脚本 simulate.py。

现在已很久没维护该项目，是否依旧可行尚未验证。

**Comment by nekocode** [comment]
已有新的解决方案，请查阅 [wechat_webview_launch.md](https://github.com/nekocode/wx_sniffer/blob/master/wechat_webview_launch.md) 文档
